name: Playwright Tests

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  run-e2es:
    runs-on: ubuntu-latest

    steps:
      - name: Print payload
        run: |
          echo "event action: ${{ github.event.action }}"
          echo '${{ toJson(github.event.client_payload) }}'

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}